version: "3.3"
services:
  hadoop:
    build: .
    ports:
      - "9000:9000"
      - "8088:8088"
      - "50070:50070"
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - "./etc/hadoop/core-site.xml:/soft/hadoop-2.9.1/etc/hadoop/core-site.xml"
      - "./etc/hadoop/hdfs-site.xml:/soft/hadoop-2.9.1/etc/hadoop/hdfs-site.xml"
      - "./etc/hadoop/mapred-site.xml:/soft/hadoop-2.9.1/etc/hadoop/mapred-site.xml"
      - "./etc/hadoop/yarn-site.xml:/soft/hadoop-2.9.1/etc/hadoop/yarn-site.xml"
      - "./jars:/jars"